[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "VQ-VAE"
authors = [{name = "Hannah Li", email = "hl3520@ic.ac.uk"}]
dynamic = ["generative model", "MNIST"]
